version: '3.9'
name: hackathon-santo-digital-test

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=AdventureWorks-test
    ports:
      - 5434:5432
    volumes:
      - ./src/main/resources/data/:/data
      - ./install.sql:/docker-entrypoint-initdb.d/install.sql
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: AdventureWorks-test
