version: '3.9'
name: hackathon-santo-digital

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - server

  database:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - server
      - adminer
  
  adminer:
    image: adminer:standalone
    depends_on:
      - database
    ports:
      - 8081:8080
    networks:
      - adminer
   
volumes:
  data:
    name: hackathon-santo-digital-db

networks:
  server:
    driver: bridge
  adminer:
    driver: bridge
