version: '3.9'
name: hackathon-santo-digital-test

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=hackathon-santo-digital-test
    ports:
      - 5434:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: hackathon-santo-digital-test
