server:
    port: 8080

spring:
    application:
        name: hackathon-santo-digital
    profiles:
        active: prod
    datasource:
        url: jdbc:postgresql://database/${DB_NAME}?useSSL=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        open-in-view: false
        defer-datasource-initialization: true
